import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
const inter = Inter({ subsets: ['latin'] });
<link
  rel='icon'
  href='./rent-a-ride-logo-zip-file/png/logo-no-background.png'
/>;

export const metadata = {
  title: 'Rent-A-Ride',
  description: 'Generated by create next app',
  icons: {
    icon: ['./rent-a-ride-logo-zip-file/png/logo-no-background.png'],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <div className='main-container'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
